export const DOCUMENT_TYPES = Object.freeze({
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
  TAX_PATENT: 'TAX_PATENT',
  IDENTITY_DOCUMENT: 'IDENTITY_DOCUMENT',
  EDITORIAL_POLICY: 'EDITORIAL_POLICY',
  OFFICE_LEASE: 'OFFICE_LEASE',
  OTHER: 'OTHER',
})
